Update capitalization typo in Open function preventing build
grid-x/serial pull request #4
Opened 2021-09-28 15:22 UTC by jbarfield

On SmartOS/ (illumos): `go build` fails with an `error: 2` regarding the `open(c)` call from within the `Open` function. This was caused by the function declaration being capitalized while the subsequent call was not. As you can see in the commit, I simply changed the call from open(c) to Open(c). Please accept my request (or update the code at your leisure if I have missed any part of the PR process for go/grid-x).

2021-09-29 08:34 UTC, gq0 commented on serial.go
> +	return Open(c)
Will this not call recursively call the outer function?

2021-09-29 08:34 UTC, gq0 commented on go.mod
> +replace github.com/grid-x/serial v0.0.0-20191104121038-e24bc9bf6f08 => github.com/jbarfield/serial v0.0.0
I guess a remnant from your repo 😉

2021-10-07 18:12 UTC, jbarfield commented on go.mod
> +replace github.com/grid-x/serial v0.0.0-20191104121038-e24bc9bf6f08 => github.com/jbarfield/serial v0.0.0
Yes, sorry about the remnant. I'll fix that. On illumos distributions, in this case specifically SmartOS, it will not build the lower case named function, it could have something to do with the use of 'cgo'. I have not gone any further down the rabbit hole though to confirm.

2021-10-12 07:30 UTC, guelfey requested changes
Sorry, but that does not make sense - it will indeed just lead to a recursive call. What is the exact error you're getting on illumos? I doubt there's something special about the `open` name

2022-01-24 01:22 UTC, jbarfield commented
After further testing I believe that it was just a warning. I do not have it up any longer. Since this was going into a pkgsrc build for telegraf I simply wrote a patch for illumos. Im closing this request.

2022-01-24 01:22 UTC, closed without merging